trigger:
- main

pool:
  name: localpool

variables:
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: 'test'
  dockerRepository: 'vladisloves/chatroom'
  imageName: '$(Build.BuildId)'

steps:
- script: |
    dotnet restore "$(Build.SourcesDirectory)/orleans/ChatRoom/ChatRoom.sln"
  displayName: 'Restore NuGet packages'
  workingDirectory: $(Build.SourcesDirectory)

- script: |
    dotnet build "$(Build.SourcesDirectory)/orleans/ChatRoom/ChatRoom.sln" --configuration $(buildConfiguration) --no-restore
  displayName: 'Build with MSBuild'
  workingDirectory: $(Build.SourcesDirectory)
  
- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'
    repository: '$(dockerRepository)'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/orleans/ChatRoom'
    tags: |
      $(imageName)
